config/routes.rb
Rails.application.routes.draw do
  resources :answer_lists
  resources :simulation_answers
  resources :tickets
  resources :alternatives
  resources :images
  resources :solutions
  resources :exam_questions
  resources :comments
  resources :profiles
  resources :memberships
  resources :simulations
  resources :questions
  resources :exams
  resources :plans
  root 'home#index'

  devise_for :users

  get 'dashboard', to: 'dashboard#index'
end

app/models/membership.rb
class Membership < ApplicationRecord
  belongs_to :user
  belongs_to :plan
end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
  before_action :set_membership, only: [:show, :edit, :update, :destroy]

  # GET /memberships
  # GET /memberships.json
  def index
    @memberships = Membership.all
  end

  # GET /memberships/1
  # GET /memberships/1.json
  def show
  end

  # GET /memberships/new
  def new
    @membership = Membership.new
  end

  # GET /memberships/1/edit
  def edit
  end

  # POST /memberships
  # POST /memberships.json
  def create
    @membership = Membership.new(membership_params)

    respond_to do |format|
      if @membership.save
        format.html { redirect_to @membership, notice: 'Membership was successfully created.' }
        format.json { render :show, status: :created, location: @membership }
      else
        format.html { render :new }
        format.json { render json: @membership.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /memberships/1
  # PATCH/PUT /memberships/1.json
  def update
    respond_to do |format|
      if @membership.update(membership_params)
        format.html { redirect_to @membership, notice: 'Membership was successfully updated.' }
        format.json { render :show, status: :ok, location: @membership }
      else
        format.html { render :edit }
        format.json { render json: @membership.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /memberships/1
  # DELETE /memberships/1.json
  def destroy
    @membership.destroy
    respond_to do |format|
      format.html { redirect_to memberships_url, notice: 'Membership was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_membership
      @membership = Membership.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def membership_params
      params.require(:membership).permit(:start_date, :expire_date, :user_id, :plan_id)
    end
end

app/views/memberships/_form.html.erb
<%= form_with(model: membership, local: true) do |form| %>
  <% if membership.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(membership.errors.count, "error") %> prohibited this membership from being saved:</h2>

      <ul>
      <% membership.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :start_date %>
    <%= form.date_select :start_date, id: :membership_start_date %>
  </div>

  <div class="field">
    <%= form.label :expire_date %>
    <%= form.date_select :expire_date, id: :membership_expire_date %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :membership_user_id %>
  </div>

  <div class="field">
    <%= form.label :plan_id %>
    <%= form.text_field :plan_id, id: :membership_plan_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/memberships/edit.html.erb
<h1>Editing Membership</h1>

<%= render 'form', membership: @membership %>

<%= link_to 'Show', @membership %> |
<%= link_to 'Back', memberships_path %>

app/views/memberships/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Memberships</h1>

<table>
  <thead>
    <tr>
      <th>Start date</th>
      <th>Expire date</th>
      <th>User</th>
      <th>Plan</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @memberships.each do |membership| %>
      <tr>
        <td><%= membership.start_date %></td>
        <td><%= membership.expire_date %></td>
        <td><%= membership.user %></td>
        <td><%= membership.plan %></td>
        <td><%= link_to 'Show', membership %></td>
        <td><%= link_to 'Edit', edit_membership_path(membership) %></td>
        <td><%= link_to 'Destroy', membership, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Membership', new_membership_path %>

app/views/memberships/new.html.erb
<h1>New Membership</h1>

<%= render 'form', membership: @membership %>

<%= link_to 'Back', memberships_path %>

app/views/memberships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Start date:</strong>
  <%= @membership.start_date %>
</p>

<p>
  <strong>Expire date:</strong>
  <%= @membership.expire_date %>
</p>

<p>
  <strong>User:</strong>
  <%= @membership.user %>
</p>

<p>
  <strong>Plan:</strong>
  <%= @membership.plan %>
</p>

<%= link_to 'Edit', edit_membership_path(@membership) %> |
<%= link_to 'Back', memberships_path %>