config/routes.rb
Rails.application.routes.draw do
  resources :answer_lists
  resources :simulation_answers
  resources :tickets
  resources :alternatives
  resources :images
  resources :solutions
  resources :exam_questions
  resources :comments
  resources :profiles
  resources :memberships
  resources :simulations
  resources :questions
  resources :exams
  resources :plans
  root 'home#index'

  devise_for :users

  get 'dashboard', to: 'dashboard#index'
end

app/models/answer_list.rb
class AnswerList < ApplicationRecord
  belongs_to :question
  belongs_to :alternative
  belongs_to :simulation_answer
end

app/controllers/answer_lists_controller.rb
class AnswerListsController < ApplicationController
  before_action :set_answer_list, only: [:show, :edit, :update, :destroy]

  # GET /answer_lists
  # GET /answer_lists.json
  def index
    @answer_lists = AnswerList.all
  end

  # GET /answer_lists/1
  # GET /answer_lists/1.json
  def show
  end

  # GET /answer_lists/new
  def new
    @answer_list = AnswerList.new
  end

  # GET /answer_lists/1/edit
  def edit
  end

  # POST /answer_lists
  # POST /answer_lists.json
  def create
    @answer_list = AnswerList.new(answer_list_params)

    respond_to do |format|
      if @answer_list.save
        format.html { redirect_to @answer_list, notice: 'Answer list was successfully created.' }
        format.json { render :show, status: :created, location: @answer_list }
      else
        format.html { render :new }
        format.json { render json: @answer_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /answer_lists/1
  # PATCH/PUT /answer_lists/1.json
  def update
    respond_to do |format|
      if @answer_list.update(answer_list_params)
        format.html { redirect_to @answer_list, notice: 'Answer list was successfully updated.' }
        format.json { render :show, status: :ok, location: @answer_list }
      else
        format.html { render :edit }
        format.json { render json: @answer_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answer_lists/1
  # DELETE /answer_lists/1.json
  def destroy
    @answer_list.destroy
    respond_to do |format|
      format.html { redirect_to answer_lists_url, notice: 'Answer list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_answer_list
      @answer_list = AnswerList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def answer_list_params
      params.require(:answer_list).permit(:question_id, :alternative_id, :simulation_answer_id)
    end
end

app/views/answer_lists/_form.html.erb
<%= form_with(model: answer_list, local: true) do |form| %>
  <% if answer_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(answer_list.errors.count, "error") %> prohibited this answer_list from being saved:</h2>

      <ul>
      <% answer_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :question_id %>
    <%= form.text_field :question_id, id: :answer_list_question_id %>
  </div>

  <div class="field">
    <%= form.label :alternative_id %>
    <%= form.text_field :alternative_id, id: :answer_list_alternative_id %>
  </div>

  <div class="field">
    <%= form.label :simulation_answer_id %>
    <%= form.text_field :simulation_answer_id, id: :answer_list_simulation_answer_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/answer_lists/edit.html.erb
<h1>Editing Answer List</h1>

<%= render 'form', answer_list: @answer_list %>

<%= link_to 'Show', @answer_list %> |
<%= link_to 'Back', answer_lists_path %>

app/views/answer_lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Answer Lists</h1>

<table>
  <thead>
    <tr>
      <th>Question</th>
      <th>Alternative</th>
      <th>Simulation answer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @answer_lists.each do |answer_list| %>
      <tr>
        <td><%= answer_list.question %></td>
        <td><%= answer_list.alternative %></td>
        <td><%= answer_list.simulation_answer %></td>
        <td><%= link_to 'Show', answer_list %></td>
        <td><%= link_to 'Edit', edit_answer_list_path(answer_list) %></td>
        <td><%= link_to 'Destroy', answer_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Answer List', new_answer_list_path %>

app/views/answer_lists/new.html.erb
<h1>New Answer List</h1>

<%= render 'form', answer_list: @answer_list %>

<%= link_to 'Back', answer_lists_path %>

app/views/answer_lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Question:</strong>
  <%= @answer_list.question %>
</p>

<p>
  <strong>Alternative:</strong>
  <%= @answer_list.alternative %>
</p>

<p>
  <strong>Simulation answer:</strong>
  <%= @answer_list.simulation_answer %>
</p>

<%= link_to 'Edit', edit_answer_list_path(@answer_list) %> |
<%= link_to 'Back', answer_lists_path %>